package enums;

public enum NombrePago {
    NOMBRE_PAGO_MENSUAL,
    NOMBRE_PAGO_BIMESTRAL,
    NOMBRE_PAGO_TRIMESTRAL,
    NOMBRE_PAGO_CUATRIMESTRAL,
    NOMBRE_PAGO_SEMESTRAL,
    NOMBRE_PAGO_ANUAL
}
